# Autogenerated wrapper script for ONNX_static_jll for i686-linux-musl-cxx11
export libonnx, libonnx_proto, libonnxifi, libonnxifi_dummy, libonnxifi_loader

JLLWrappers.@generate_wrapper_header("ONNX_static")
JLLWrappers.@declare_file_product(libonnx)
JLLWrappers.@declare_file_product(libonnx_proto)
JLLWrappers.@declare_library_product(libonnxifi, "libonnxifi.so")
JLLWrappers.@declare_library_product(libonnxifi_dummy, "libonnxifi_dummy.so")
JLLWrappers.@declare_file_product(libonnxifi_loader)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libonnx,
        "lib/libonnx.a",
    )

    JLLWrappers.@init_file_product(
        libonnx_proto,
        "lib/libonnx_proto.a",
    )

    JLLWrappers.@init_library_product(
        libonnxifi,
        "lib/libonnxifi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi_dummy,
        "lib/libonnxifi_dummy.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libonnxifi_loader,
        "lib/libonnxifi_loader.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
